[#ftl]
[@b.head/]
[@b.grid  items=columnsStatisticses var="columnsStatistics" sortable="false"]
	[@b.row]
		[#--[@b.boxcol/]--]
		[@b.col width="20%" property="columns.site.name" title="所属站点" ]${(columnsStatistics[1])?if_exists}[/@]
		[@b.col width="30%" property="columns.name" title="栏目排序" ]${(columnsStatistics[2])?if_exists}[/@]
		[@b.col width="40%" property="columns.name" title="栏目名称" ]${(columnsStatistics[0])?if_exists}[/@]
		[@b.col width="10%" property="views" title="访问量" ]
			[@b.a href="!detail?orders=${columnsStatistics[2]}"]
				${(columnsStatistics[3])?if_exists}
			[/@]
		[/@]
	[/@]
[/@]
[@b.foot/]