[#ftl]
[@b.head/]
	[@b.form action="!search" title="ui.searchForm" target="courseList" theme="search"]
		[@b.select name="course.enabled" label="common.status" items={'true':'有效','false':'无效'}  empty="状态"/]
		[@b.select name="professionalId" label="专业" items=professionals option="id,name" empty="请选择..."/]
		[@b.select name="course.courseType.id" label="课程性质" items=courseTypes option="id,name" empty="请选择..."/]
		[@b.textfields names="course.name;名称"/]
		[@b.textfields names="course.code;代码"/]
		[@b.startend label="发布日期,-" name="start,end" required="false,false" format="date"/]
	[/@]
	[@b.div  href="!search" id="courseList" class="dataList"/]
[@b.foot/]
