[#ftl]
[@b.navmenu title="课程信息"]
	[@ems.guard res="/course/course"]
		[@b.navitem title="基本信息" href="/course/course!edit?courseId=${course.id!}"/]
		[#if course.id??]
			[@b.navitem title="课程概况" href="/course/course!courseColumnList?courseId=${course.id!}" /]
			[#--[@b.navitem title="课程标准" href="/course/course!courseStandard?courseId=${course.id!}"/]--]
			[@b.navitem title="课程章节" href="/course/course-section!search?courseId=${course.id!}" /]
			[@b.navitem title="课程内容" href="/course/course-content!search?courseId=${course.id!}" /]
			[@b.navitem title="相关课程" href="/course/course-related!search?courseId=${course.id!}" /]
			[@b.navitem title="参考教材" href="/course/course-book!search?courseId=${course.id!}" /]
		[/#if]
	[/@]
[/@]