[#ftl]
[@b.head/]
[@b.toolbar title="课程栏目" entityId=courseColumn.id!0]bar.addBack();[/@]
[@b.form action="!save" title="课程栏目" theme="list"]
	[@b.textfield label="栏目名称" name="courseColumn.name" value="${courseColumn.name!}" style="width:200px;" required="true" maxlength="100" /]
	[@b.select label="栏目类型" name="courseColumn.columnType.id" value=(courseColumn.columnType.id)! style="width:200px;" required="true" items=columnTypes option="id,name" empty="请选择..."/]
	[@b.select label="上级栏目" name="parent.id" value=(courseColumn.parent.id)! style="width:200px;"  items=parents option="id,description" empty="请选择..."/]
	[@b.textfield label="课程字段" name="courseColumn.courseField" value="${(courseColumn.courseField)!}" style="width:200px;" maxlength="100" /]
	[@b.textfield label="访问地址" name="courseColumn.url" value="${(courseColumn.url)!}" required="true" style="width:200px;" maxlength="100" /]
	[@b.textfield label="同级顺序号" name="indexno" value="${courseColumn.indexno!}" required="true" maxlength="3" check="match('integer').range(1,999)" /]
	[@b.radios name="courseColumn.enabled" label="是否有效" value=courseColumn.enabled items="1:有效,0:无效"/]
	[@b.textarea label="描述"  name="courseColumn.remark" maxlength="100" value=courseColumn.remark! rows="3" cols="40"/]
	[@b.formfoot]
		[@b.reset/]&nbsp;&nbsp;
		[@b.submit value="action.submit" /]
		[@b.redirectParams/]
		<input type="hidden" name="courseColumn.id" value="${courseColumn.id!}" />
	[/@]
[/@]
[@b.foot/]