[#ftl]
[@b.head/]
	[@b.form action="!search?orderBy=code" title="ui.searchForm" target="courseColumnlist" theme="search"]
		[@b.select name="courseColumn.enabled" label="common.status" items={'true':'有效','false':'无效'}  empty="..."/]
		[@b.select name="courseColumn.columnType.id" label="栏目类型" items=columnTypes  empty="栏目类型"/]
		[@b.textfields names="courseColumn.name;栏目名称"/]
	[/@]
	[@b.div  href="!search?orderBy=code" id="courseColumnlist" class="dataList"/]
[@b.foot/]
