[#ftl]
[@b.head/]
[@b.form name="pjglSearchForm"  action="!search" target="pjglList" title="ui.searchForm" theme="search"]
	[@b.textfields names="wenJuanPj.wjmc;问卷名称"/]
	[@b.textfields names="wenJuanPj.sm;说明"/]
	[@b.select name="wenJuanPj.enabled" label="common.status" items={'true':'已发布','false':'未发布'} empty="..."/]
[/@]
[@b.div id="pjglList" href="!search" /]
[@b.foot/]