[#ftl]
[@b.head/]
	[@b.form action="!search?orderBy=professional.code" title="ui.searchForm" target="professionalList" theme="search"]
		[@b.select name="professional.enabled" label="common.status" items={'true':'有效','false':'无效'}  empty="状态"/]
		[@b.textfields names="professional.name;名称"/]
		[@b.textfields names="professional.code;代码"/]
	[/@]
	[@b.div  href="!search?orderBy=professional.code" id="professionalList" class="dataList"/]
[@b.foot/]
