[#ftl]
[@b.head/]
	[@b.form name="tiKuSearchForm"  action="!search" target="tiKulist" title="ui.searchForm" theme="search"]
		[@b.textfields names="tiKu.tkmc;题库名称"/]
		[@b.select items=types empty="..." name="tiKu.tkfl.id" label="题库分类" option="id,name"/]
		[@b.select name="tiKu.enabled" label="common.status" value="" empty="..." items={'1':'有效','0':'无效'}/]
	[/@]
	[@b.div id="tiKulist" href="!search" /]
[@b.foot/]