[#ftl]
[@b.head/]
	[@b.form name="ksapSearchForm"  action="!search" target="ksaplist" title="ui.searchForm" theme="search"]
		[@b.select label="状态" name="ksap.enabled"  value="1" empty="..." items={'1':'有效','0':'无效'}/]
		[@b.select label="类型"  name="ksap.type.id"  empty="..."   items=types option="id,name" /]
		[@b.select label="类别"  name="ksap.category.id"  empty="..."   items=categorys option="id,name" /]
		[@b.textfields names="ksap.name;名称"/]
		[@b.select label="问卷"  name="ksap.wenJuan.id"  empty="..."   items=wenJuans option="id,name" /]
	[/@]
	[@b.div id="ksaplist" href="!search?ksap.enabled=1" /]
[@b.foot/]