[#ftl]
[@b.head/]
[@b.form name="djwjSearchForm"  action="!search" target="dcwjList" title="ui.searchForm" theme="search"]
	[@b.select name="wenJuanDc.enabled" label="common.status" items={'true':'已发布','false':'未发布'} empty="..."/]
	[@b.select name="wenJuanDc.wjlx.id" items=wjlxs label="类型" empty="..."/]
	[@b.textfields names="wenJuanDc.wjmc;问卷名称"/]
[/@]
[@b.div id="dcwjList" href="!search" /]
[@b.foot/]