[#ftl]
[@b.head/]
[@b.form action="!search" name="ksapSearchForm" id="ksapSearchForm"]
[@b.grid  items=ksaps var="ksap" sortable="false" filterable="false"]
	[@b.gridbar]
	[/@]
	[@b.row]
		[@b.col width="30%" title="学习过程" property="name"/]
		[@b.col width="15%" title="开始时间"  align="center"]
			${(ksap.startTime?string("yyyy-MM-dd HH:mm"))!}
		[/@]
		[@b.col width="15%" title="结束时间"  align="center"]
			${(ksap.endTime?string("yyyy-MM-dd HH:mm"))!}
		[/@]
		[@b.col width="20%" title="考试总时长（分钟）" property="time"  align="center"][/@]
		[@b.col width="10%" title="考试类型" property="type.name"/]
		[@b.col width="10%" title="操作" align="center"]
			[@b.a href="!edit?ksap.id=${ksap.id}" onclick="this.disabled=true;return bg.Go(this,null,true);"][答卷][/@]
		[/@]
	[/@]
[/@]
[/@]
[@b.foot/]