[#ftl]
[@b.head/]
[@b.form name="sjglSearchForm"  action="!search" target="sjglList" title="ui.searchForm" theme="search"]
	[@b.textfields names="wenJuan.wjmc;问卷名称"/]
	[@b.select name="wenJuan.wjlx.id" items=wjlxs label="类型" empty="..."/]
	[@b.select name="wenJuan.enabled" label="common.status" items={'true':'已发布','false':'未发布'} empty="..."/]
[/@]
[@b.div id="sjglList" href="!search" /]
[@b.foot/]