[#ftl]
[@b.head/]
[@b.grid  items=contentStatisticses var="contentStatistics" sortable="false"]
	[@b.row]
		[#--[@b.boxcol/]--]
		[@b.col width="20%" property="columns.site.name" title="所属站点" ]${(contentStatistics[0])?if_exists}[/@]
		[@b.col width="30%" property="columns.name" title="栏目名称" ]${(contentStatistics[2])?if_exists}[/@]
		[@b.col width="40%" property="content.title" title="信息标题" ]${(contentStatistics[3])?if_exists}[/@]
		[@b.col width="10%" property="views" title="访问量" ]
			[@b.a href="!detail?contentId=${contentStatistics[5]}"]
				${(contentStatistics[4])?if_exists}
			[/@]
		[/@]
	[/@]
[/@]
[@b.foot/]