[#ftl]
[@b.head/]
[@b.toolbar title="课程" entityId=course.id!0]bar.addBack();[/@]
[#include "../course/nav.ftl"/]
[@b.grid  items=courseRelateds var="courseRelated"]
	[@b.gridbar]
		bar.addItem("${b.text("action.add")}",action.add());
		bar.addItem("${b.text("action.delete")}",action.remove());
	[/@]
	[@b.row]
		[@b.boxcol/]
		[@b.col width="20%" property="courseRelated.code" title="课程代码" /]
		[@b.col width="26%" property="courseRelated.name" title="课程名称" /]
		[@b.col width="22%" property="courseRelated.courseType.name" title="课程性质" /]
		[@b.col width="28%" title="专业"]
			[#list courseRelated.courseRelated.professionals as professional]
				${(professional.name)!}[#if professional_has_next]<br>[/#if]
			[/#list]
		[/@b.col]
	[/@]
[/@]
[@b.foot/]