[#ftl]
[@b.head/]
<script type="text/javascript" src="${base}/static/scripts/comm/jquery.blockUI.js"></script>
[@b.grid  items=courses var="course"]
	[@b.row]
		[@b.col width="10%" property="code" title="课程代码" /]
		[@b.col width="16%" property="name" title="课程名称" /]
		[@b.col width="12%" property="courseType.name" title="课程性质" /]
		[@b.col width="18%" title="专业"]
			[#list course.professionals as professional]
				${(professional.name)!}[#if professional_has_next]<br>[/#if]
			[/#list]
		[/@b.col]
		[@b.col width="10%" property="courseLeader.fullname" title="课程负责人" /]
		[@b.col width="10%" title="发布日期" ]
			${(course.publishAt?string("yyyy-MM-dd"))!}
		[/@]
		[@b.col width="25%" title="操作" ]
			[@b.a href="!courseColumnList?courseId=${course.id!}"]课程栏目[/@]
			[@b.a href="/course/course-section!search?courseId=${course.id!}"]课程章节[/@]<br>
			[@b.a href="/course/course-content!search?courseId=${course.id!}"]课程内容[/@]
			[@b.a href="/course/course-book!search?courseId=${(course.id)!}"]参考教材[/@] 
			[@b.a href="/course/course-home!index?courseId=${(course.id)!}"]课程主页[/@] 
		[/@]
	[/@]
[/@]
[@b.foot/]