[#ftl]
[@b.head/]
[#import "/org/beangle/wenjuan/action/zuJuan/WenJuan.ftl" as wj]
[@b.grid  items=zxkss var="zxks"]
	[@b.gridbar]
	[/@]
	[@b.row]
		[@b.col width="20%" title="学习过程名称" property="ksap.name"/]
		[@b.col width="15%" title="学员姓名" property="user.fullname" /]
		[@b.col width="15%" title="考试类型" property="ksap.type.name"/]
		[@b.col width="20%" title="开考时间"]${(zxks.wjjg.startTime?datetime)!}[/@]
		[@b.col width="20%" title="交卷时间"]${(zxks.wjjg.endTime?datetime)!}[/@]
		[@b.col width="10%" title="分数" property="wjjg.score"  align="center" ][#if zxks.wjjg??][@wj.showScore wjjg=zxks.wjjg/][/#if][/@]
	[/@]
[/@]
[@b.foot/]