[#ftl]
[@b.head/]
[#include "../nav.ftl"/]
[@b.div]
[@b.form name="workflowSearchForm"  action="!search" target="workflowlist" title="ui.searchForm" theme="search"]
	[@b.textfields names="workflow.code;流程代码,workflow.name;流程名称"/]
[/@]
[@b.div id="workflowlist" href="!search" /]
[/@]
[@b.foot/]